First draft for experimental ACP proposal docs
inrupt/docs-client-lib-js pull request #27
Opened 2020-10-29 16:47 UTC by Vinnl

These docs are _very_ dry, because the API's are so low-level that the documentation is mostly just an enumeration of the functions that are available and how they map to the low-level ACP functionality, which is considered prerequisite knowledge for this tutorial.

2020-10-29 20:53 UTC, kay-kim approved these changes
Thanks Vincent.  LGTM.
There are some small typos and some copy-editing/reorganizing that I'll do post merge.
The question I won't be able to answer is the disclaimers.  That I'll leave for @nicolasmondada  and @oolivo  to decide.  (because with ESS, we're stating not to use WAC in production - so ...).

2020-10-30 08:31 UTC, Vinnl commented
I think both can be true - WAC is not in a great state and should probably not be used, but if you want to try out ACPs, you better be ready to invest a considerable resources in maintaining your implementation and working closely with Inrupt, or just not working on a production-grade app. If people go in with different expectations, they will be severely disappointed.

2020-10-30 13:56 UTC, kay-kim commented
Yup.  I was just flagging Oz and NickM since they'll be more attuned to the exact wording of the messages.  Whereas the other content, I think I should be able to go forth with the editing and such.

2020-11-02 00:41 UTC, nicolasmondada commented
This is a great first pass. Excellent. 

Since ACPs are going to be the default option on ESS, it should reflect on the documentation. We should refer to ACP on Manage Access to Data and have WAC on a lower level/compat mode. Docs for WAC should still be accessible but it should be clear ACPs are the one to use. @kay-kim can you take care of this?

I'll add more comments inline.

2020-11-02 08:09 UTC, Vinnl commented
@nicolasmondada Makes sure to make it absolutely clear then that that will only work for users who are talking against a Pod server that supports ACPs (preferably with explicit mention of inrupt.net and solidcommunity.net _not_ supporting it yet), since this documentation is read by the community as well, who will not be exclusively (if at all) working with their own Pod server like enterprise partners might do initially.

2020-11-02 09:15 UTC, NSeydoux approved these changes

2020-11-02 09:15 UTC, NSeydoux commented on source/tutorial/experimental-access-control-policies-preview.rst
> +   Policies proposal, and is primarily intended for internal use by
Is there any public place where the proposal is documented ? I think it was supposed to be introduced to the panel soon, but I don't know if it's public in the meantime.

2020-11-02 09:15 UTC, NSeydoux commented on source/tutorial/experimental-access-control-policies-preview.rst
> +the Resource's children can be accessed using ``getAcrPolicyUrlAll`` and
```suggestion
the Resource's children can be accessed using respectively ``getAcrPolicyUrlAll`` and
```

2020-11-02 09:15 UTC, NSeydoux commented on source/tutorial/experimental-access-control-policies-preview.rst
> +Access Controls can be obtained using ``getControl`` and ``getControlAll``,
I guess a more complete glossary will be available once the proposal is public, and/or when we provide a high-level, actually public API, as opposed as this currently low-level API meant for people familiar with the vocabulary of the ACP proposal ?

2020-11-02 09:15 UTC, NSeydoux commented
I was a bit concerned that the change was 500-lines long, but I think half of it comes from license headers ^^

2020-11-02 11:37 UTC, nicolasmondada requested changes

2020-11-02 11:41 UTC, nicolasmondada commented
> @nicolasmondada Makes sure to make it absolutely clear then that that will only work for users who are talking against a Pod server that supports ACPs (preferably with explicit mention of inrupt.net and solidcommunity.net _not_ supporting it yet), since this documentation is read by the community as well, who will not be exclusively (if at all) working with their own Pod server like enterprise partners might do initially.

That's a good point. We need to be clear that Solid servers have two different access control modes and ACP is the default for ESS (might be different for other servers)

2020-11-02 11:47 UTC, Vinnl commented on source/tutorial/experimental-access-control-policies-preview.rst
> +   will be added to the Resource with an Access Control Resource directly.
This sentence is not about the higher-level API, but about (breaking) changes to the lower-level API.

2020-11-02 11:48 UTC, Vinnl commented on source/tutorial/experimental-access-control-policies-preview.rst
> +aware of is that a Policy always has a full known URL that Access Controls can
Yes, you have to come up with it on your own. The developer has to decide where to store a Policy.

2020-11-02 12:18 UTC, Vinnl commented on source/examples/acp-rule-public.js
> +// but it does apply to everybody who is authenticated.
Hmm yeah, that's clearer, thanks.

2020-11-02 12:21 UTC, Vinnl commented on source/tutorial/experimental-access-control-policies-preview.rst
> +   Policies proposal, and is primarily intended for internal use by
There will be separate documentation that explains ACPs. That should link to the proposal (wherever it is), and we should link back to it from this documentation.

2020-11-02 12:23 UTC, Vinnl commented on source/tutorial/experimental-access-control-policies-preview.rst
> +Access Controls can be obtained using ``getControl`` and ``getControlAll``,
Yeah I'm not sure what to do about the glossary, as there are some terms that are equal to WAC terms, but mean something different in the context of ACPs. @kay-kim any guidance here?

2020-11-02 12:24 UTC, Vinnl commented on source/tutorial/experimental-access-control-policies-preview.rst
> +the Resource's children can be accessed using ``getAcrPolicyUrlAll`` and
Applied with preservation of line wrapping in 6701e1c1b23deb96a62b4f33f8f0f129d8c49412.

2020-11-02 12:52 UTC, kay-kim commented on source/tutorial/experimental-access-control-policies-preview.rst
> +Access Controls can be obtained using ``getControl`` and ``getControlAll``,
So ... we should differentiate in the definition.

For example, since Control Access is ACL only:
`Control Access
    Access to view and manage who has access to the applicable Resource.
    Applicable to the :term:`ACL` authorization system.
`
If for both, maybe remove the ACL specific mention in the definition.
`
Access Modes
       The types of access available. 
       - :term:`Read Access`
       - :term:`Append Access`
       - :term:`Write Access`
       - :term:`Control Access`
`
But, just FYI. So for the "concept" part of ACP, I'll end up adding the following to the top of your page. 

<img width="1021" alt="Screen Shot 2020-11-02 at 7 51 09 AM" src="https://user-images.githubusercontent.com/2126636/97869913-3311f900-1ce0-11eb-9f7b-a636b795e40d.png">

2020-11-02 14:33 UTC, kay-kim commented on source/tutorial/experimental-access-control-policies-preview.rst
> +   Policies proposal, and is primarily intended for internal use by
As discussed in our Oct 26th meetings, the documentation to explain ACP will be at the top of this page (similar to how we're introducing the concepts for the manage ACL page).  See the image below.

2020-11-02 14:48 UTC, merged