Update use-vocabularies.rst
inrupt/docs-client-lib-js pull request #28
Opened 2020-10-29 16:48 UTC by nicolasmondada

Updated title and first paragraph.

2020-10-29 18:27 UTC, kay-kim requested changes

2020-10-29 18:27 UTC, kay-kim commented on source/tutorial/use-vocabularies.rst
> +in their data entities. This facilitates interoperability between Solid applications.
Do we need the second sentence? Also, heh, I believe @pmcb55  is not in favor of the term "facilitates" (but, eh, everyone has their own idiosyncrasies).

2020-10-29 18:27 UTC, kay-kim commented on source/tutorial/use-vocabularies.rst
> +each term is associated with a unique identifier (:term:`IRI`).
Is the intent to reduce ambiguity across Vocabularies?  If so, probably should tweak this sentence.

2020-10-29 20:15 UTC, nicolasmondada commented on source/tutorial/use-vocabularies.rst
> +each term is associated with a unique identifier (:term:`IRI`).
Yes, ambiguity across vocabs. E.g.: http://schema.org/familyName vs http://www.w3.org/2006/vcard/ns#family-name. Please go ahead and tweak it as you see fit.

2020-10-29 20:16 UTC, nicolasmondada commented on source/tutorial/use-vocabularies.rst
> +in their data entities. This facilitates interoperability between Solid applications.
The objective of that second sentence is to explain why Solid apps use vocabs. Feel free to change it and use different words.

2020-11-05 00:06 UTC, pmcb55 commented on source/tutorial/use-vocabularies.rst
> +in their data entities. This facilitates interoperability between Solid applications.
Re. 'facilitates' - yeah, I'd just uses 'helps' here instead. (Although it's missing a '**_how_** vocabularies help' as a follow-on sentence, so maybe needs extension:
`This helps greatly with interoperability between Solid applications if developers choose to reuse commonly known existing vocabularies, such as [Schema.org](https://schema.org) or [vCard](https://www.w3.org/TR/vcard-rdf/), or when developers create their own new vocabularies that they share, and that then become popular with other developers in their field or problem domain.`

2020-11-05 00:18 UTC, pmcb55 commented on source/tutorial/use-vocabularies.rst
> +each term is associated with a unique identifier (:term:`IRI`).
Yeah, I talked to Nick about this today, and I think there have already been changes - i.e. a table with 'term' and 'identifier' columns. Likewise, in the `master` branch now, at the end of this file is a couple of Person examples:
```
  - `Schema.org`_ identifier ``http://schema.org/familyName``,

  - `Schema.org`_ identifier ``https://schema.org/givenName``, and

  - `vCard`_ identifier ``http://www.w3.org/2006/vcard/ns#email``.

- Someone else may also identify their data entities as
  ``http://schema.org/Person`` but with different properties, e.g.:

  - `Schema.org`_ identifier ``https://schema.org/telephone`` and

  - `Schema.org`_ identifier ``https://schema.org/name``.
```
...but I'd just try and show terms not from Schema.org at all (i.e. you have a vCard term in the first example, which is great, but I'd replace `http://schema.org/familyName` with `FOAF:givenName` and perhaps use `https://www.w3.org/ns/person#birthName` just as an example of pulling terms from very different vocabs (i.e. I don't know if anyone really uses that Person vocab, but it looks interesting to me, and illustrates the point of 'I can use a vocab from anywhere').

2020-11-05 00:38 UTC, kay-kim commented on source/tutorial/use-vocabularies.rst
> +each term is associated with a unique identifier (:term:`IRI`).
Great. Can make changes to the properties as am currently introducing Shapes  where it constrains the type to ``http://www.w3.org/2006/vcard/ns#Individual`` (in which case, both examples would fail).  Before anyone gets mildly happy that I'm finally mentioning the word "Shapes" in our client library docs, it'll be more like examples where you can/cannot save data.  It'll be somewhat brief (until our products offer more in the way that relates).  What can I say, I'm a company gal. 

In which case, @nicolasmondada  - any objections if I just close this pull?

2020-11-05 17:19 UTC, kay-kim commented
Closing as superseded by Pat's https://github.com/inrupt/docs-client-lib-js/pull/38

2020-11-05 17:19 UTC, closed without merging